export const DEFAULT_WORDS = [
  'Bubbel eller Champagne',
  'Skåla eller skråla',
  'Dansa eller supa',
  'Mingel eller fest',
  'Hångel eller sång',
  'Snyggast i rummet',
  'Klassiskt nyårslöfte',
  'Bästa deli-osten',
  'Hip-hop eller hårdrock?',
  'Bästa julfilmen',
  'Bakismat',
  'Alkoholfri dryck',
  'Alkoholhaltig dryck',
  'Bästa vin-landet',
];
